#include "hash_tables.h"

/**
 * key_index - gives the index of the key
 * @key: The key(string)
 * @size: size of the array of the hash table
 * Description: The function generates an index from the key given
 *  and the size specified.
 *  The index must be between Zero (0) and Hash table size.
 *  Therefore, the modulus of the hash value generated by djb2 algo
 *  will be less than the hash table size and that will be the index.
 * Return: The key index.
 */

unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int hash = hash_djb2(key);

	/* Set index to be less than hash table size */
	hash = hash % size;

	return (hash);
}
